name: "Install rpk"
description: "Install the rpk binary from Redpanda"
author: "Redpanda Data"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "download"
  color: "blue"

# Define your inputs here.
inputs:
  version:
    description: 'Version of rpk to install (e.g. "latest" or "1.2.3")'
    required: false
    default: "latest"

runs:
  using: node20
  main: dist/index.js
