name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        id: enable-corepack
        run: corepack enable

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install Dependencies
        id: yarn-install
        run: yarn install --immutable

      - name: Check Format
        id: yarn-format-check
        run: yarn format:check

      - name: Lint
        id: yarn-lint
        run: yarn lint

      - name: Test
        id: yarn-ci-test
        run: yarn ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          version: latest

      - name: Verify Installation
        id: verify
        run: |
          rpk version
          which rpk
